### ISSUE TITLE
Clicking on the status area quits the program with an error

### ISSUE THREAD

**Issue by dkim286** [dkim286/cpsc362-proj#2]
Expected behavior: 

- Clicking on the status area should do nothing.

Current behavior: 

- Clicking on the status area quits the program unexpectedly.

Trace:

```
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/person/courses/soft eng/cpsc362-proj/main.py", line 21, in <module>
    main()
  File "/home/person/courses/soft eng/cpsc362-proj/main.py", line 18, in main
    board.run()
  File "/home/person/courses/soft eng/cpsc362-proj/ttt/board.py", line 74, in run
    self.drawToken()
  File "/home/person/courses/soft eng/cpsc362-proj/ttt/board.py", line 129, in drawToken
    location = GRID_OFFSETS[row - 1][col - 1]
TypeError: unsupported operand type(s) for -: 'NoneType' and 'int'
```

**Comment by dkim286** [comment]
resolved by https://github.com/dkim286/cpsc362-proj/commit/2ff8640700ad62ffe76825dbc8ef24b648e4eb92
