### ISSUE TITLE
game crashes on startup 

### ISSUE THREAD

**Issue by dkim286** [dkim286/cpsc362-proj#9]
regression in commit https://github.com/dkim286/cpsc362-proj/commit/86e13d576075f16bec203750308fb868866a403e

```
$ python main.py 
pygame 2.0.1 (SDL 2.0.14, Python 3.9.5)
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "/home/person/courses/soft eng/cpsc362-proj/main.py", line 21, in <module>
    main()
  File "/home/person/courses/soft eng/cpsc362-proj/main.py", line 18, in main
    board.run()
  File "/home/person/courses/soft eng/cpsc362-proj/ttt/board.py", line 84, in run
    cpu_move = cpu.find_best_move()
  File "/home/person/courses/soft eng/cpsc362-proj/ttt/cpu.py", line 42, in find_best_move
    for col in rand_cols:
NameError: name 'rand_cols' is not defined
```

Please, at least run the game once before committing changes. This isn't difficult.

**Comment by kavyavandana** [comment]
Fix is merged into main - https://github.com/dkim286/cpsc362-proj/commit/874f732fe762fd9e12aa0db0d6242f4499bd031f

**Comment by dkim286** [comment]
resolved by https://github.com/dkim286/cpsc362-proj/commit/874f732fe762fd9e12aa0db0d6242f4499bd031f
